### ISSUE TITLE
Bonemeal works on crops when it shouldn't

### ISSUE THREAD

**Issue by PitchBright** [JakobOvrum/BiomeCrops#2]
When I try to fertilize a crop with bonemeal, in a biome that it is configured to not-grow in… bonemeal still forces the crop to grow.

Normally, the message in the console when a crop gets a growth tick is:

"growth tick or fertilize event for recognized block"

so that lead me to believe that when a crop isn't supposed to grow in a biome, bonemeal (fertilize event) shouldn't work on it. Is that the case?

Also worth noting is that when I use bonemeal on a crop… there is no output in the console regarding the action. (There's no "growth tick or fertilize event for recognized block" message, specifically).

**Comment by JakobOvrum** [comment]
Bonemeal is not implemented yet. I was initially trying to use AppleCore's functionality for this (in the newer version) which is why the log message indicates bonemeal support, but BiomeCrops is strangely incompatible with the newer version. I think there is a Forge event that can be used for simple disabling of bonemeal events, so that's probably the way to go.
